substitutions:
  name: econet
  device_description: "Communicate with Econet Netork"
  tx_pin: GPIO19
  rx_pin: GPIO22

esphome:
  name: ${name}
  comment: ${device_description}
  project:
    name: "stockmopar.econet"
    version: 0.1.0

esp32:
  board: esp32dev
  framework: 
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:

logger:
#  baud_rate: 0  # Disable UART logger if using UART0 (pins 1,3)
  level: DEBUG
  tx_buffer_size: 2000

external_components:
#  - source: github://stockmopar/esphome-econet
#  - source: components
  - source:
      type: local
      path: ./components

uart:
  id: uart_0
  baud_rate: 38400
  rx_buffer_size: 1500
  tx_pin: 
    number: ${tx_pin}
  rx_pin:
    number: ${rx_pin}

# The base UART communication hub.
econet:
  uart: uart_0
  model: "Electric_Tank"

climate:
  - platform: econet
    name: "Water Heater"

# Optional additional sensors.
sensor:
  - platform: econet
    hot_water:
      name: "Hot Water"
    setpoint:
      name: "Set Point Temperature"
    heatctrl:
      name: "Heater Control"
    lower_water_heater_temp:
      name: "Lower Tank Temperature"
    upper_water_heater_temp:
      name: "Upper Tank Temperature"
    power_watt:
      name: "Power"

binary_sensor:
  - platform: econet
    enable_state:
      name: "Water Heater Enabled (Sensor)"

switch:
  - platform: econet
    name: "Water Heater Enabled"
    switch_datapoint: 0
    id: wh_enabled_switch

